<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>GuidedArrow.Progression</AssemblyName>
    <RootNamespace>GuidedArrow.Progression</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>1.3.4</Version>
    <FileVersion>1.3.4.0</FileVersion>
    <AssemblyVersion>1.3.4.0</AssemblyVersion>
    <BannerlordReferenceVersion Condition="'$(BannerlordReferenceVersion)' == ''">1.3.15.110062</BannerlordReferenceVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <EnableSourceLink>false</EnableSourceLink>
    <PublishRepositoryUrl>false</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
    <SourceRevisionId>0000000000000000000000000000000000000000</SourceRevisionId>
    <RepositoryCommit>0000000000000000000000000000000000000000</RepositoryCommit>
    <PathMap>$(MSBuildProjectDirectory)=/_/src/GuidedArrow.Progression</PathMap>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bannerlord.ReferenceAssemblies.Core" Version="$(BannerlordReferenceVersion)" />
    <PackageReference Include="Bannerlord.ReferenceAssemblies.Native" Version="$(BannerlordReferenceVersion)" PrivateAssets="All" />
    <PackageReference Include="Lib.Harmony" Version="2.4.1" PrivateAssets="All" />
    <PackageReference Include="Bannerlord.MCM" Version="5.12.1" IncludeAssets="compile" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
